### ISSUE TITLE
remove unneccessary files

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-types#2]
@Thomaash Do we need these files here? Or can I purge them?
- package.json
- tsconfig.json
- tslint.json
- vis-tests.ts

**Comment by Thomaash** [comment]
I have never worked with type only package so I don't know what is the purpose of any of them. TSLint is deprecated so you can definitely purge that (we can use ESLint instead if the need arises).

**Comment by mojoaxel** [comment]
done
